// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --env-file=.env ./src/config/db.seed.ts",
  },
  datasource: {
    // url: process.env["DATABASE_URL"] as string,
    url: env("DATABASE_URL")
  },
});
